# Complete web interface with Firestore backend for production
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env.production
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/credentials.json
    volumes:
      - ./credentials.json:/app/credentials/credentials.json:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    command: npm start
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
