services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env.local
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/credentials.json
    volumes:
      - ./backend/app:/app/app
      - ./credentials.json:/app/credentials/credentials.json:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    command: npm start
    restart: unless-stopped